### PR TITLE
Report api prototype

### PR DESCRIPTION
**Pull request by cacraig**
Requirements for deployment:
- Add environment variables to all *.env files:

``` bash
export DB_DRIVER=[mongodb,rethinkdb]
export TABLE_NAME=[epa,ed,nasa, ...]
export DB_HOST=
export DB_PORT=
export DB_NAME=
export DB_USERNAME=
export DB_PASSWORD=
```

RethinkDB
- Install RethinkDB >2.0.0
- run npm install

OR

MongoDB
- Install MongoDB > 3.0.0
- run npm install

Usage:

``` bash
https://<ANALYTICS_URL>/api/v1.0/:agency/:report?start_date=YYYY-MM-DD&end_date=YYYY-MM-DD

```

``` bash
example:
https://www.analytics.usa.gov/api/v1.0/epa/devices?start_date=2016-01-27&end_date=2016-01-28
```

**result**

``` json

[
  {
    "date": "2016-01-28T00:00:00.000Z",
    "device": "desktop",
    "visits": "144"
  },
  {
    "date": "2016-01-28T00:00:00.000Z",
    "device": "mobile",
    "visits": "26"
  },
  {
    "date": "2016-01-28T00:00:00.000Z",
    "device": "tablet",
    "visits": "4"
  }, ... ]
```

Notes:
- Stores time series data for all reports with the "ga:date" dimension. Merges results, so it will be a continuous dataset.
- All other reports are stored as-is, and replaced when updated.

todo:
- Accept limit, order, and sort parameters.
- Add response codes. 500, 400, 403(?Add API keys?), 200.
- Add more agencies -> Add ability to get sub-agency level data.

### CODE REVIEW

**Comment by konklone** [comment]
One major thing I'd like to see here is the DB-level work moved into its own file. Right now, there's a lot of direct DB access going on in both `bin/analytics` and `analytics.js`. Those files would ideally remain nearly untouched by this addition, and nearly all of the API-specific code would be in its own file/module.

**Comment by cacraig** [comment]
@konklone Good point, I'll encapsulate the DB within it's own module.

**Comment by cacraig** [comment]
@konklone  - I made the following changes:
  
(1) Moved DB stuff off to it's own module,  
(2) Deferred loading of this module to ensure DB config info is defined for the environment.  
  
Assuming everything is 👍  , how should we go about deploying this? As I mentioned ^^^ I'm going to need to install Rethinkdb, and add environment vars on prod/test environments.

**Comment by konklone** [comment]
@cacraig Let's take it to Slack so we can talk through 18F-specific operations and deployment issues. Not that it's sensitive, it's just not pertinent to other repo watchers.

**Comment by cacraig** [comment]
@konklone I added a MongoDB driver for this API, and made it a bit more generic. Thanks for all the feedback thusfar! We can continue on the deployment stuff on slack.

**Pull request closed without merging**
