### PR TITLE
Added agencies to crontab [HOLD]

### PR DESCRIPTION
**Pull request by cacraig**
Added 15 agencies.

Following .env files needed:

Department of Agriculture   -> agriculture.env
Department of Defense  -> defense.env
Department of Health and Human Services -> hhs.env
Department of Housing and Urban Development -> hud.env
Department of Homeland Security -> dhs.env
Department of Labor -> labor.env
Department of State -> state.env
Department of Transportation -> transportation.env
Department of the Treasury -> treasury.env
Agency for International Development -> usaid.env
General Services Administration -> gsa.env
National Science Foundation -> nsf.env
Nuclear Regulatory Commission -> nrc.env
Office of Personnel Management -> opm.env
Social Security Administration -> ssa.env

### CODE REVIEW

**Comment by cacraig** [comment]
See https://github.com/18F/analytics.usa.gov/issues/365 for UI additions.

**Comment by konklone** [comment]
The production server now has the specified env files in place, and the crontab is set to use them. I've updated the `crontab`, `daily.sh`, `hourly.sh`, and `realtime.sh` files in this PR with what the production server now uses.

The agency-specific env files are not in this PR. Should we add them, or to some other repo?

**Comment by konklone** [comment]
I added a commit with the 25 agency env files we've created that govern analytics-reporter.

**Comment by cacraig** [comment]
Everything looks in order. Merging.

**Pull request merged**
