### PR TITLE
General cleanup

### PR DESCRIPTION
**Pull request by jmhooper**
This PR moves a lot of things around and pulls out what looked to me like dead code. Feedback is very welcome here, because I'm still familiarizing myself with some of the dependencies folks using `analytics-reporter` have.

### Delete `app` directory

I deleted the little express app living the `app` directory. I looked through the blame, and it looked like it's been a little over a year since anyone has touched it. Additionally, I tried starting it up and it crashed because it was trying to use templates that don't exist.

That was enough evidence for me to declare it dead code and delete it.

### Move analytics.js out of `bin` directory

I moved the `analytics.js` file, which exports the `run` and `publish` functions, from `bin/analytics.js` to `index.js`. This seemed like a more appropriate place for it since it seems to contain most of the outward facing logic for the reporter.

Additionally, I modified the executable in `bin/analytics` to call out to the new `index.js` file, instead of having a copy of its contents.

### Delete `bin/cron.js`

This file looked like it would work, but maybe not the way you'd expect it too since it does not specify a frequency in the options it passes to `analytics.run()`. Also, it does not appear to handle multiple reports. For these reasons I deleted it.

### Move `analytics.js` and `config.js` into `src` directory

I created a `src` directory and moved the files that provide supporting logic / configuration into it. I'd like to think we can modularize these components a bit more once we have tests. I thought it wise to give them some room to grow away from the project root.

### CODE REVIEW

**Comment by jmhooper** [comment]
Ref 18f/analytics.usa.gov#423

**Comment by jmhooper** [comment]
I also bumped the node version in `package.json` to `>= 7.0.0` to sneak some ES6 in there. I didn't tell Travis about that so the tests are red now.

I'm not sure what our requirements are regarding the version of node we use? Any issues going to 7? That's what it is running on in cloud.gov right now.

**Comment by konklone** [comment]
@polastre Are you still using the contents of the `app` directory at Medium?

> I'm not sure what our requirements are regarding the version of node we use? Any issues going to 7? That's what it is running on in cloud.gov right now.

@jmhooper Ever forward!

**Comment by polastre** [comment]
@konklone nope, not anymore.

**Comment by konklone** [comment]
Then :+1: from me.

**Pull request merged**
