### PR TITLE
Refactor [WIP]

### PR DESCRIPTION
**Pull request by geramirez**
This refactor splits the code into multiple exportable modules in a way that might be easier to incorporate into other apps. It's code I wrote a while back, but would like to revisit.

### CODE REVIEW

**Comment by konklone** [comment]
The nature of the refactor makes the diff hard to understand. Can you explain in prose what this does?

**Comment by geramirez** [comment]
@konklone, so the refactor keeps the same CLI but allows us to deploy to CloudFoundry or Heroku more easily like this: https://github.com/geramirez/analytics-reporter-example/blob/master/server.js

**Comment by konklone** [comment]
So this wouldn't use `cf-cron` or a Heroku background task, but would use Node's repeated timeouts to keep background processing going?

**Comment by konklone** [comment]
In any case, can you annotate some of the diff, or otherwise outline some of the changes you made to support `server.js`? As I said, the collective diff is too sweeping to follow along with. If there's a couple of good isolated commits that show the meat of the work, I'm happy to look at those instead.

**Pull request closed without merging**
