### PR TITLE
Allow for empty / lack of data rows and removed 1000 filters in reports.json

### PR DESCRIPTION
**Pull request by dorianjp**
Analytics.js: Check for empty data rows and produces empty report rather than throwing an exception
reports.json: removed sub1000 filters which skews results on smaller sites.

### CODE REVIEW

**Comment by konklone** [comment]
Great, I'm very happy to make sure the tool gracefully handles empty reports.

We should really start a small test suite, so that we can verify behavior and prevent regressions like you identified in #89.

Also, we need to find a way we can accommodate both small and large sites -- I know analytics.usa.gov _needs_ a sub-1000 filter. While we may need to refactor the whole system eventually, one intermediate step would be to specify in `reports.json` that a report should be filterable for large sites, and then use an environment/config variable (e.g. `ANALYTICS_VISITS_THRESHOLD`) that, if set, adds the `filter` query parameter with the value of the variable.

@dorianjp, would you mind reverting the sub-1000 change, so that we can merge just the error handling for empty data, and handle filters separately?

**Comment by dorianjp** [comment]
I took out the changes to reports.json
But I agree we need a common threshold param or an option to have no filter at all.

**Comment by konklone** [comment]
(I'm merging this in, but for future PRs, please align your whitespace settings with ours -- we're using spaces, not tabs, and it's causing the diff to be unnecessarily tricky to read in places.)

**Comment by konklone** [comment]
I've merged it in, but adjusted it in https://github.com/18F/analytics-reporter/commit/6e04ba5c590b615fa0e504ad49d9a4587a7eb547 to:

* use one big conditional instead of two
* normalize spacing
* move the date-stamping up to the top
* limit the conditional that skips counting rows to when the `totalResults` is 0, so that this only skips data processing in the case of an empty result. I want other kinds of unexpected bugs that cause `data.rows` to be null to properly fail.

Thank you for the contribution!

**Comment by dorianjp** [comment]
Fantastic!

**Pull request merged**
