### PR TITLE
Add docker image badges

### PR DESCRIPTION
**Pull request by paolomainardi**
This MR adds 2 microbadger.com badges based on the docker hub images, would be nice to add https://shields.io/ build badge but i don't get how should be used (and if it can) for any open source project.

Preview: https://github.com/paolomainardi/analytics-reporter/blob/3b8b92e34873b132b08eb233d61dfc64410b20b2/README.md

### CODE REVIEW

**Comment by abitrolly** [comment]
@paolomainardi looks like microbadger.com is shut down.

**Comment by paolomainardi** [comment]
@abitrolly you replied to a thing of 5 years ago - I don’t even know what is this

**Comment by abitrolly** [comment]
@paolomainardi yea, well, this is open PR related to that thing. Maybe close it then?

**Comment by paolomainardi** [comment]
Closed, thanks for raising this up.

**Pull request closed without merging**
