### PR TITLE
Support for session limiter as 'sessions' parameter

### PR DESCRIPTION
**Pull request by dorianjp**
Default is no limiting
Updated reports.json to remove limit, added 'sessions=true' for indicator to filter by sessions
updated bin/analytics for param input and modifying the json accordingly

### CODE REVIEW

**Comment by dorianjp** [comment]
Woops, I built this branch off my previous commit instead of your master. If there are issues with the empty report fix, i suppose I can rebase. But if the empty row fix is approved, then this change is only related to the 'sessions' param.

**Comment by konklone** [comment]
So I think the better approach here is to set it as an environment variable (and thus `config` value), rather than add another command line flag. The weight of adding a command line flag every time is heavier than letting another environment variable sit around.

To be honest, environment variable soup is also annoying, but some sort of flag is necessary unless/until we refactor the app to use a different approach to report specification.

**Comment by dorianjp** [comment]
the more I think about it, we're just recreating the google reporting api interface here. Perhaps just adjust the documentation to mention that the "query" dictionary in reports.json was built as a template of predefined queries from the Google reporting API here.
https://developers.google.com/analytics/devguides/reporting/core/v3/reference
Tweak / adjust as needed.
This way, others using the project have eyes open as to the query spec, not to mention the metadata in the reports which people likely would want to change anyways "US gov etc."

**Comment by konklone** [comment]
> the more I think about it, we're just recreating the google reporting api interface here. 

Yep, these are the limits of the static approach.

> This way, others using the project have eyes open as to the query spec, not to mention the metadata in the reports which people likely would want to change anyways "US gov etc."

We did get rid of the "US gov" language in a recent commit.

OK, I'll close this for now. Of course, one other approach might be to unversion `reports.json`, or to make multiple JSON files for different kinds of use cases, and point the tool towards looking at one of them through env vars -- rather than using env vars to micromanage each parameter.

**Comment by laurenancona** [comment]
@konklone I'd been thinking about creating different ```reports.json``` for different use cases; +1 for that.
Locally, I'd been thinking about it more granularly for roles in government, but at the federal level it would be perfect for sub-reports like social media engagement/traffic or performance metrics.

**Comment by konklone** [comment]
@laurenancona Yeah -- maybe we can make a `reports/` directory with a bunch of individual JSON files within it that act like profiles. I mean, we could also make `reports.json` an unversioned file, and expect individual users to create their own, but I guess it just feels like if we can save people work, without increasing code complexity, I don't mind storing a bunch of JSON files in this repo that address different use cases.

**Pull request closed without merging**
